# This is a basic workflow to help you get started with Actions

name: CI
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Generate new index.html
      run: python ./bin/generate_index.py
      
    - name: Add & Commit new index.html
      uses: EndBug/add-and-commit@v4.2.1
      with:
          message: "Setting mantra for TODAY"
          add: "./docs/index.html"
          author_name: "Github Daily Action"
          author_email: "kamori.goat@gmail.com"

